# Generated by Django 2.2.4 on 2020-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('assignment_title', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('submission_date', models.CharField(max_length=100)),
            ],
        ),
    ]
