# Generated by Django 2.2.4 on 2020-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('lecture_title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
